server:
  port: 8080

spring:

  datasource:
    #*******************H2*********************************#
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  #*******************H2*********************************#
  jpa:
    #*******************H2*********************************#
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  #*******************H2*********************************#

  #*******************H2*********************************#
  h2:
    console:
      enabled: true
      path: /h2
  #*******************H2*********************************#